"""Render a character from a recipe over the labeled template.

Pipeline per frame (all steps are label/tone driven, so one recipe covers every frame):
  1. materials: each body part gets a color ramp; the template tone picks the ramp slot
     (base/shade/light/blush), so the template's shading carries over automatically.
  2. rules: small procedural details from label geometry (trim where two parts touch,
     a stripe along a part's center, top/bottom rows of a part).
  3. head overlays: per-facing pixel grids in head-local coordinates, placed with the
     head tracking of each frame (hair, visor, ...).
  4. outline: optional recolor of the ink outline.

Left facings (down_side_l, side_l, up_side_l) are generated by mirroring the right
facings and swapping the anatomical sides of the labels, so asymmetric designs
(one cyber arm, an undercut) stay on the correct side of the body.
"""
from __future__ import annotations

import json
import tomllib
from dataclasses import dataclass, replace
from pathlib import Path

import numpy as np
from PIL import Image

from .catalog import DIRS, TONE_IDS, Template
from .labels import GROUPS, PARTS, load_all

FACINGS = ["down", "down_side", "side", "up_side", "up", "down_side_l", "side_l", "up_side_l"]
SIDE_SWAP = str.maketrans("RLrlPQpq", "LRlrQPqp")
PART_CODES = {v: k for k, v in PARTS.items()}
HEAD_PAD = 3  # head grids extend this many pixels around the head template


def hex_rgb(s: str) -> tuple[int, int, int]:
    s = s.lstrip("#")
    return tuple(int(s[i:i + 2], 16) for i in (0, 2, 4))


def part_codes(name: str) -> str:
    """'torso' -> 'T', 'arms' -> 'RL', 'none' -> '.', 'arm_r+hand_r' -> 'Rr'."""
    out = ""
    for n in name.split("+"):
        if n == "none":
            out += "."
        elif n in GROUPS:
            out += GROUPS[n]
        elif n in PART_CODES:
            out += PART_CODES[n]
        else:
            raise KeyError(f"unknown part/group {n!r}")
    return out


@dataclass
class Frame:
    """One output frame before coloring: tones, labels, head placement, facing."""
    tones: np.ndarray
    labels: np.ndarray
    head: tuple[str, int, int, int] | None  # (facing, x, y, width) of the head template
    facing: str
    duration: int


def _merge(base: dict, over: dict) -> dict:
    out = dict(base)
    for k, v in over.items():
        out[k] = _merge(out[k], v) if isinstance(v, dict) and isinstance(out.get(k), dict) else v
    return out


def load_recipe_data(path: Path) -> dict:
    """TOML recipe; `extends = "other"` deep-merges on top of characters/other/recipe.toml.
    Tables merge key by key, arrays (rules) replace unless `extra_rules` appends."""
    data = tomllib.loads(path.read_text())
    if "extends" in data:
        base = load_recipe_data(path.parent.parent / data.pop("extends") / "recipe.toml")
        extra = data.pop("extra_rules", [])
        data = _merge(base, data)
        data["rules"] = data.get("rules", []) + extra
    return data


# What the head-grid tools may assume about legend characters: `hair` cells are the mane (kept
# on the last drafted row, the volume `--shift` probes), `texture` a second surface treated like
# hair when cleaning (a shaved side, a hat band), `lens` the row(s) of an eyepiece (its rows and
# their neighbours are exempt from the visor cleanup), `rim` the eyepiece's frame characters (moved
# off other rows by `--clean`), `caps` what `--mirror-swap` puts at a lens's ends. These are Juno's
# characters; a recipe overrides any of them in `[head.classes]`.
HEAD_CLASSES = {"hair": "kbHDi", "texture": "uUw", "lens": "v", "rim": "xf", "caps": "x"}


class Recipe:
    def __init__(self, path: Path):
        self.path = path
        self.data = load_recipe_data(path)
        self.name = self.data.get("name", path.parent.name)
        self.ramps = {k: {slot: hex_rgb(c) for slot, c in v.items()} for k, v in self.data.get("palette", {}).items()}
        self.parts = self.data.get("parts", {})
        self.rules = self.data.get("rules", [])
        self.outline = self.data.get("outline", {})
        head = self.data.get("head", {})
        self.legend = head.get("legend", {})
        self.head_classes = {**HEAD_CLASSES, **head.get("classes", {})}
        self.grids = {f: _parse_grid(g) for f, g in head.get("grids", {}).items()}
        missing = [f + "_l" for f in ("down_side", "side", "up_side") if f in self.grids and f + "_l" not in self.grids]
        if missing:  # the mirrored fallback puts an asymmetric haircut on the wrong side
            import sys
            print(f"warning: {path.name}: no grid for {', '.join(missing)}; the right-facing grid is mirrored "
                  f"(wrong for a one-sided haircut or visor)", file=sys.stderr)

    def emissive_colors(self) -> set[tuple[int, int, int]]:
        """Every color of the ramps listed in `emissive` (they glow in the dark)."""
        return {tuple(c) for name in self.data.get("emissive", []) for c in self.ramps[name].values()}

    def color(self, ref: str, tone: int) -> tuple[int, int, int] | None:
        """'#rrggbb' fixed color, 'ramp' tone-relative, 'ramp.slot' fixed slot, 'ink' keeps outline."""
        if ref.startswith("#"):
            return hex_rgb(ref)
        if ref == "clear":
            return None
        ramp, _, slot = ref.partition(".")
        r = self.ramps[ramp]
        if slot:
            return r[slot]
        return ramp_slot(r, tone)


def ramp_slot(r: dict, tone: int) -> tuple[int, int, int]:
    if tone == TONE_IDS["shade"]:
        return r.get("shade", r["base"])
    if tone == TONE_IDS["light"]:
        return r.get("light", r.get("shade", r["base"]))
    if tone == TONE_IDS["blush"]:
        return r.get("blush", r.get("light", r["base"]))
    if tone == TONE_IDS["ink"]:
        return r.get("ink", (47, 37, 34))
    return r["base"]


def _parse_grid(text: str) -> np.ndarray:
    rows = [r for r in text.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    return np.array([list(r.ljust(w, ".")) for r in rows], "<U1")


# ---------------------------------------------------------------- frame layout

def build_frames(tpl: Template) -> dict[str, dict[str, list[Frame]]]:
    """anims[anim][facing] -> frames, including mirrored left facings."""
    labels = load_all(tpl)
    out: dict[str, dict[str, list[Frame]]] = {}
    for anim, dirs in tpl.anims.items():
        out[anim] = {}
        for d, idx in dirs.items():
            frames = [_frame(tpl, labels, i, d) for i in idx]
            out[anim][d if anim != "rotate" else "all"] = frames
            if d in ("down_side", "side", "up_side"):
                out[anim][d + "_l"] = [_mirror(f, tpl.w) for f in frames]
    return out


def _frame(tpl: Template, labels: np.ndarray, i: int, d: str) -> Frame:
    fit = tpl.head_fits[i]
    facing = fit.dir + ("_l" if fit.flip and fit.dir not in ("down", "up") else "")
    w = tpl.heads[fit.dir].shape[1]
    body_facing = d if d in DIRS else facing
    return Frame(tpl.tones[i], labels[i], (facing, fit.x, fit.y, w), body_facing, tpl.durations[i])


def _mirror(f: Frame, W: int) -> Frame:
    hf, x, y, w = f.head
    hf = hf[:-2] if hf.endswith("_l") else (hf + "_l" if hf not in ("down", "up") else hf)
    lab = np.vectorize(lambda c: c.translate(SIDE_SWAP))(f.labels[:, ::-1])
    facing = f.facing + "_l" if f.facing not in ("down", "up") else f.facing
    return Frame(f.tones[:, ::-1], lab, (hf, W - x - w, y, w), facing, f.duration)


# ---------------------------------------------------------------- rendering

def render_frame(r: Recipe, f: Frame) -> np.ndarray:
    H, W = f.tones.shape
    rgba = np.zeros((H, W, 4), np.uint8)
    op = f.tones > 0
    ink = f.tones == TONE_IDS["ink"]
    # 1. materials. Later [parts] entries override earlier ones, so list groups first.
    rgba[op] = (47, 37, 34, 255)
    for name, ramp in r.parts.items():
        m = np.isin(f.labels, list(part_codes(name))) & op
        for y, x in zip(*np.where(m)):
            t = f.tones[y, x]
            if t == TONE_IDS["ink"] and "ink" not in r.ramps[ramp]:
                continue  # keep template ink (outlines, eyes) unless the ramp defines one
            rgba[y, x, :3] = ramp_slot(r.ramps[ramp], t)
    # 2. rules. With `rule_facing = "head"` they follow the tracked head's facing, so
    #    trim turns with the body in spinning poses (the attack) instead of staying put;
    #    with `"body"` the head's side is kept but front/back comes from the labels (her
    #    right arm left of her left arm means she faces the camera), so a head that turns
    #    before the body does not put the back collar across her chest.
    if r.data.get("rule_facing") in ("head", "body") and f.head:
        facing = f.head[0]
        if r.data.get("rule_facing") == "body":
            facing = _body_facing(f, facing)
        f = replace(f, facing=facing)
    for rule in r.rules:
        if "facings" in rule and f.facing not in rule["facings"]:
            continue
        if rule["type"] == "grow":
            f = _grow(rule, f, rgba, r)
            continue
        if rule["type"] == "shrink":
            f = _shrink(rule, f, rgba)
            continue
        mask = _rule_mask(rule, f)
        for y, x in zip(*np.where(mask)):
            t = f.tones[y, x]
            # a rule that asked to paint ink pixels means "this material here", so a ramp
            # without an ink slot paints its shade rather than falling back to template ink
            if rule.get("ink") and t == TONE_IDS["ink"] and "." not in rule["color"] and not rule["color"].startswith("#"):
                if "ink" not in r.ramps.get(rule["color"], {}):
                    t = TONE_IDS["shade"]
            c = r.color(rule["color"], t)
            rgba[y, x] = (*c, 255) if c else (0, 0, 0, 0)
    # 3. head overlays
    painted = np.full((H, W), ".", "<U1")
    if f.head and r.grids:
        painted = _apply_head(r, f, rgba)
    # 4. outline: ink pixels that touch transparency (the silhouette edge);
    #    head-grid pixels painted with a legend char listed in `keep` stay as drawn.
    #    `color` is a hex or a ramp reference, so a colorway can swap it with the palette.
    #    The ink mask is taken from the frame as the rules left it: `grow` moves edges.
    if "color" in r.outline:
        a = rgba[..., 3] > 0
        ink = f.tones == TONE_IDS["ink"]
        edge = ink & a & ~_erode(a) & ~np.isin(painted, list(r.outline.get("keep", "")))
        rgba[edge, :3] = r.color(r.outline["color"], TONE_IDS["base"])
        # `parts`: a part's own line colour (selective outlining: dark trousers edged in a
        # cool black, skin and hair in the warm brown); later entries win, like [parts]
        for name, ref in r.outline.get("parts", {}).items():
            m = edge & np.isin(f.labels, list(part_codes(name))) & (painted == ".")
            rgba[m, :3] = r.color(ref, TONE_IDS["base"])
    return rgba


def _body_facing(f: Frame, head_facing: str) -> str:
    """The head's facing with its front/back taken from the arms' order in the labels."""
    xr = np.where(np.isin(f.labels, ["R", "r"]) & (f.tones > 0))[1]
    xl = np.where(np.isin(f.labels, ["L", "l"]) & (f.tones > 0))[1]
    if not len(xr) or not len(xl):
        return head_facing
    d = xl.mean() - xr.mean()  # > 0: her right is on the left, she faces the camera
    left = head_facing.endswith("_l")
    base = head_facing[:-2] if left else head_facing
    if d > 1.5 and base in ("up", "up_side"):
        base = {"up": "down", "up_side": "down_side"}[base]
    elif d < -1.5 and base in ("down", "down_side"):
        base = {"down": "up", "down_side": "up_side"}[base]
    return base + ("_l" if left and base != "down" and base != "up" else "")


def _grow(rule: dict, f: Frame, rgba: np.ndarray, r: Recipe) -> Frame:
    """`grow`: push a part's silhouette out by `n` pixels on the given `sides` (default
    all), into transparent pixels only. The part's edge pixel moves outward (so the
    outline stays an outline) and the pixel it left becomes `color`. The frame's tones
    and labels grow with it, so later rules see the bigger part. Bigger shoes on a
    template whose feet are two pixels wide, for example."""
    tones, lab = f.tones.copy(), f.labels.copy()
    codes = list(part_codes(rule["part"]))
    steps = {"up": (-1, 0), "down": (1, 0), "left": (0, -1), "right": (0, 1)}
    H, W = tones.shape
    sides = []
    for side in rule.get("sides", list(steps)):
        if side in ("front", "back"):  # the facing's front side; left facings are mirrored
            side = "left" if (side == "front") == f.facing.endswith("_l") else "right"
        sides.append(side)
    for _ in range(rule.get("n", 1)):
        part = np.isin(lab, codes) & (tones > 0)
        for side in sides:
            dy, dx = steps[side]
            for y, x in zip(*np.where(part)):
                ny, nx = y + dy, x + dx
                if not (0 <= ny < H and 0 <= nx < W) or tones[ny, nx] > 0:
                    continue
                rgba[ny, nx] = rgba[y, x]
                tones[ny, nx], lab[ny, nx] = tones[y, x], lab[y, x]
                if tones[y, x] == TONE_IDS["ink"]:  # the edge moved out: fill behind it
                    c = r.color(rule["color"], TONE_IDS["base"])
                    rgba[y, x] = (*c, 255)
                    tones[y, x] = TONE_IDS["base"]
    return replace(f, tones=tones, labels=lab)


def _shrink(rule: dict, f: Frame, rgba: np.ndarray) -> Frame:
    """`shrink`: the inverse of `grow`. Pull a part's silhouette in by `n` pixels on the given
    `sides` (default all): the part's edge pixels on that side (a transparent neighbour in the
    side's direction) are erased, and the pixel behind each becomes ink, so the outline pass
    still finds an edge. Tones and labels shrink with it. A mockup two pixels narrower than the
    mannequin at the sleeves, for example."""
    tones, lab = f.tones.copy(), f.labels.copy()
    codes = list(part_codes(rule["part"]))
    steps = {"up": (-1, 0), "down": (1, 0), "left": (0, -1), "right": (0, 1)}
    H, W = tones.shape
    sides = []
    for side in rule.get("sides", list(steps)):
        if side in ("front", "back"):  # the facing's front side; left facings are mirrored
            side = "left" if (side == "front") == f.facing.endswith("_l") else "right"
        sides.append(side)
    for _ in range(rule.get("n", 1)):
        for side in sides:
            dy, dx = steps[side]
            part = np.isin(lab, codes) & (tones > 0)
            op = tones > 0  # a snapshot: the edge is judged before anything is erased, or it cascades inward
            edge = [(y, x) for y, x in zip(*np.where(part))
                    if not (0 <= y + dy < H and 0 <= x + dx < W and op[y + dy, x + dx])]
            for y, x in edge:
                rgba[y, x] = 0
                tones[y, x], lab[y, x] = 0, "."
            for y, x in edge:
                by, bx = y - dy, x - dx  # the pixel behind becomes the new edge: ink
                if 0 <= by < H and 0 <= bx < W and tones[by, bx] > 0 and lab[by, bx] in codes:
                    tones[by, bx] = TONE_IDS["ink"]
                    rgba[by, bx] = (47, 37, 34, 255)
    return replace(f, tones=tones, labels=lab)


def _erode(a: np.ndarray) -> np.ndarray:
    p = np.pad(a, 1)
    return p[1:-1, 1:-1] & p[:-2, 1:-1] & p[2:, 1:-1] & p[1:-1, :-2] & p[1:-1, 2:]


def _rule_mask(rule: dict, f: Frame) -> np.ndarray:
    lab, tones = f.labels, f.tones
    part = np.isin(lab, list(part_codes(rule["part"])))
    # `only_if_ink`: only in frames where the template draws the part entirely in ink (a far
    # limb swinging behind the body is a dark silhouette), e.g. to keep the material readable
    if rule.get("only_if_ink") and (part & (tones != TONE_IDS["ink"])).any():
        return np.zeros_like(part)
    if not rule.get("ink", False):
        part &= tones != TONE_IDS["ink"]
    kind = rule["type"]
    if kind == "edge":
        # part pixels whose neighbor (in the given sides) belongs to `touching`
        other = np.isin(lab, list(part_codes(rule["touching"])))
        p = np.pad(other, 1)
        nb = {"up": p[:-2, 1:-1], "down": p[2:, 1:-1], "left": p[1:-1, :-2], "right": p[1:-1, 2:]}
        sides = rule.get("sides", list(nb))
        hit = np.zeros_like(part)
        for s in sides:
            hit |= nb[s]
        return part & hit
    if kind == "rows":
        # the first/last n rows of the part's interior, per frame
        ys = np.where(part.any(axis=1))[0]
        out = np.zeros_like(part)
        if len(ys):
            n = rule.get("n", 1)
            sel = ys[:n] if rule.get("from", "bottom") == "top" else ys[-n:]
            out[sel] = part[sel]
        return out
    if kind == "stripe":
        # a vertical line through the part's per-row center (or `anchor` = "left"/"right"
        # or "front"/"back" edge), shifted by `offset` (mirrored on left facings, like the
        # frame itself); `top` limits it to the part's first n rows
        out = np.zeros_like(part)
        anchor = rule.get("anchor", "center")
        if anchor in ("front", "back"):  # the facing's front edge; left facings are mirrored
            anchor = "left" if (anchor == "front") == f.facing.endswith("_l") else "right"
        all_rows = np.where(part.any(axis=1))[0]
        rows = all_rows[:rule.get("top")]

        def base_x(y):
            xs = np.where(part[y])[0]
            return {"left": xs[0], "right": xs[-1]}.get(anchor, int(round((xs[0] + xs[-1]) / 2)))
        # `straight`: one column for the whole part (the median over ALL its rows, so stacked
        # stripes with different `top`s form one strip even when a grow widens the top rows),
        # so a zipper stays a straight line on twisted poses instead of zig-zagging row by row
        fixed = int(np.median([base_x(y) for y in all_rows])) if rule.get("straight") and len(all_rows) else None
        for y in rows:
            base = fixed if fixed is not None else base_x(y)
            x = base + rule.get("offset", 0) * (-1 if f.facing.endswith("_l") else 1)
            if 0 <= x < part.shape[1] and part[y, x]:
                out[y, x] = True
        return out
    if kind == "region":
        # the first `n` pixels of every row from the anchored side ("left"/"right", or the
        # facing's "front"/"back"): a panel of the part, e.g. the far flank of the torso
        anchor = rule.get("anchor", "back")
        if anchor in ("front", "back"):
            anchor = "left" if (anchor == "front") == f.facing.endswith("_l") else "right"
        out = np.zeros_like(part)
        n = rule.get("n", 1)
        rows = np.where(part.any(axis=1))[0][rule.get("skip", 0):]  # `skip`: rows left out at the top
        for y in rows[:rule.get("top")]:
            xs = np.where(part[y])[0]
            sel = xs[:n] if anchor == "left" else xs[-n:]
            out[y, sel] = True
        return out
    if kind == "band":
        # one row at fraction `at` (0 = top, 1 = bottom) of the part's vertical extent;
        # with `anchor` only one pixel of that row (placed like a stripe)
        ys = np.where(part.any(axis=1))[0]
        out = np.zeros_like(part)
        if len(ys):
            y = ys[0] + int(round(rule.get("at", 0.5) * (ys[-1] - ys[0])))
            if "anchor" in rule:
                row = np.zeros_like(part)
                row[y] = part[y]
                return _rule_mask({**rule, "type": "stripe", "top": None}, f) & row
            out[y] = part[y]
        return out
    if kind == "all":
        return part
    raise ValueError(f"unknown rule type {kind}")


def _apply_head(r: Recipe, f: Frame, rgba: np.ndarray) -> np.ndarray:
    """Paint the facing's head grid; returns the grid char painted at each pixel ('.' = none)."""
    facing, hx, hy, _hw = f.head
    grid = r.grids.get(facing)
    if grid is None and facing.endswith("_l") and facing[:-2] in r.grids:
        grid = r.grids[facing[:-2]][:, ::-1]
        # mirrored grid must stay aligned to the mirrored head template width
    H, W = f.tones.shape
    painted = np.full((H, W), ".", "<U1")
    if grid is None:
        return painted
    allowed = np.isin(f.labels, ["H", "N", "."])
    for gy, gx in zip(*np.where(grid != ".")):
        y, x = hy + gy - HEAD_PAD, hx + gx - HEAD_PAD
        if not (0 <= y < H and 0 <= x < W) or not allowed[y, x]:
            continue
        ref = r.legend[grid[gy, gx]]
        c = r.color(ref, f.tones[y, x])
        rgba[y, x] = (*c, 255) if c else (0, 0, 0, 0)
        painted[y, x] = grid[gy, gx]
    return painted


# ---------------------------------------------------------------- export

ANIM_ORDER = ["idle", "walk", "run", "jump", "attack", "interact", "rotate"]


def export(tpl: Template, recipe: Recipe | None, out_dir: Path) -> Path:
    """Write sheet.png + sheet.json: one row per (anim, facing), frames left to right."""
    frames = build_frames(tpl)
    rows = []
    for anim in ANIM_ORDER:
        for facing, fr in frames[anim].items():
            rows.append((anim, facing, fr))
    cols = max(len(fr) for *_, fr in rows)
    sheet = np.zeros((len(rows) * tpl.h, cols * tpl.w, 4), np.uint8)
    meta = {"name": recipe.name if recipe else "template", "frame_w": tpl.w, "frame_h": tpl.h,
            "facings": FACINGS, "anims": {}}
    light = (recipe.data.get("light") or {}) if recipe else {}
    anchor = part_codes(light["anchor"]) if "anchor" in light else None
    strong = {}  # emissive strength per part (emissive_parts), else emissive_strength
    if recipe:
        for part, v in recipe.data.get("emissive_parts", {}).items():
            strong[part_codes(part)] = v
    labels = np.full(sheet.shape[:2], ".", "<U1")
    for ri, (anim, facing, fr) in enumerate(rows):
        entry = []
        for ci, f in enumerate(fr):
            px = render_frame(recipe, f) if recipe else _identity(tpl, f)
            sheet[ri * tpl.h:(ri + 1) * tpl.h, ci * tpl.w:(ci + 1) * tpl.w] = px
            labels[ri * tpl.h:(ri + 1) * tpl.h, ci * tpl.w:(ci + 1) * tpl.w] = f.labels
            e = {"x": ci * tpl.w, "y": ri * tpl.h, "ms": f.duration}
            if anchor:  # where the light sits in this frame: the anchor part's centroid
                ys, xs = np.where(np.isin(f.labels, list(anchor)) & (f.tones > 0))
                if len(xs):
                    e["light"] = [round(float(xs.mean()), 1), round(float(ys.mean()), 1)]
            entry.append(e)
        meta["anims"].setdefault(anim, {})[facing] = entry
    out_dir.mkdir(parents=True, exist_ok=True)
    Image.fromarray(sheet).save(out_dir / "sheet.png")
    glow = recipe.emissive_colors() if recipe else set()
    if glow:  # self-lit pixels (e.g. the visor): the game draws these unlit on top
        rgb = sheet[..., :3].reshape(-1, 3).astype(np.int64)
        mask = np.isin(rgb[:, 0] * 65536 + rgb[:, 1] * 256 + rgb[:, 2],
                       [r * 65536 + g * 256 + b for r, g, b in glow]).reshape(sheet.shape[:2])
        em = sheet.copy()
        em[~(mask & (sheet[..., 3] > 0))] = 0
        # alpha = how self-lit: emissive_strength, overridden per body part by emissive_parts
        alpha = np.full(sheet.shape[:2], recipe.data.get("emissive_strength", 1.0))
        for codes, v in strong.items():
            alpha[np.isin(labels, list(codes))] = v
        em[..., 3] = np.where(em[..., 3] > 0, np.round(alpha * 255), 0).astype(np.uint8)
        Image.fromarray(em).save(out_dir / "sheet_emissive.png")
        meta["emissive"] = {"sheet": "sheet_emissive.png", "light": light or None}
    (out_dir / "sheet.json").write_text(json.dumps(meta, indent=1))
    return out_dir


_TONE_RGB = {TONE_IDS[k]: v for k, v in
             {"base": (250, 243, 232), "shade": (185, 179, 161), "light": (231, 213, 198),
              "blush": (209, 157, 167), "ink": (47, 37, 34)}.items()}


def _identity(tpl: Template, f: Frame) -> np.ndarray:
    out = np.zeros(f.tones.shape + (4,), np.uint8)
    for t, c in _TONE_RGB.items():
        out[f.tones == t] = (*c, 255)
    return out
